// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vvending_machine.cpp"
#include "Vvending_machine___024root__DepSet_hbe87a0e9__0.cpp"
#include "Vvending_machine___024root__DepSet_ha6ba58d0__0.cpp"
#include "Vvending_machine__Trace__0.cpp"
#include "Vvending_machine___024root__Slow.cpp"
#include "Vvending_machine___024root__DepSet_hbe87a0e9__0__Slow.cpp"
#include "Vvending_machine___024root__DepSet_ha6ba58d0__0__Slow.cpp"
#include "Vvending_machine__Syms.cpp"
#include "Vvending_machine__Trace__0__Slow.cpp"
#include "Vvending_machine__TraceDecls__0__Slow.cpp"
